iuginP/pps-17-cw-mp

.travis.yml, doc/agile/travis configuration.travis.yml
- https://trello.com/c/1GsT0cu0
=> [SPRINT1] Creato file yml per travis

server/authentication/src/main/scala/it/cwmp/authentication/AuthenticationServiceVerticle.scala, server/authentication/src/main/scala/it/cwmp/authentication/HttpUtils.scala, server/authentication/src/test/scala/it/cwmp/authentication/AuthenticationServiceTest.scala, server/authentication/src/test/scala/it/cwmp/storage/StorageAsyncTest.scala
- https://trello.com/c/pxGAUT7Q
=> [SPRINT1] corretto e completato test per l'autenticazione

server/authentication/build.gradle, server/authentication/src/main/scala/it/cwmp/authentication/AuthenticationServiceVerticle.scala, server/authentication/src/main/scala/it/cwmp/storage/StorageAsync.scala, server/authentication/src/test/scala/it/cwmp/authentication/AuthenticationServiceTest.scala
- https://trello.com/c/pxGAUT7Q
=> [SPRINT1] implementazione dell'autenticazione con lo storage

server/authentication/build.gradle, server/authentication/src/main/scala/it/cwmp/authentication/AuthenticationServiceVerticle.scala, server/authentication/src/main/scala/it/cwmp/authentication/HttpUtils.scala, server/authentication/src/main/scala/it/cwmp/authentication/JwtUtils.scala, server/authentication/src/main/scala/it/cwmp/storage/StorageAsync.scala, server/authentication/src/test/scala/it/cwmp/authentication/AuthenticationServiceTest.scala, server/authentication/src/test/scala/it/cwmp/authentication/JwtUtilsTest.scala
- https://trello.com/c/pxGAUT7Q
=> [SPRINT1] completato autenticazione con JWT e test

core/build.gradle, core/src/main/scala/it/cwmp/authentication/AuthenticationService.scala, core/src/test/scala/it/cwmp/authentication/AuthenticationServiceTest.scala, server/authentication/src/test/scala/it/cwmp/authentication/AuthenticationServiceTest.scala
- [IT2] https://trello.com/c/ezSZK6Wr
=> [SPRINT2] AuthenticationService helper (functionalities wrapper)

core/src/main/scala/it/cwmp/authentication/AuthenticationService.scala, core/src/test/scala/it/cwmp/authentication/AuthenticationServiceTest.scala
https://github.com/iuginP/pps-17-cw-mp/pull/13
=> [SPRINT2] AuthenticationService helper (functionalities wrapper) - corretto valore di ritorno

client/src/main/resources/openingLayout.fxml, client/src/main/resources/signInLayout.fxml, client/src/main/scala/it/cwmp/ClientMain.scala, client/src/main/scala/it/cwmp/controller/AuthenticationController.scala, client/src/main/scala/it/cwmp/controller/OpeningController.scala, client/src/main/scala/it/cwmp/controller/ViewController.scala, client/src/main/scala/it/cwmp/utils/LayoutRes.scala, client/src/main/scala/it/cwmp/utils/StringRes.scala, client/src/main/scala/it/cwmp/utils/ViewUtils.scala, client/src/main/scala/it/cwmp/view/OpeningView.scala, client/src/main/scala/it/cwmp/view/SignInView.scala, client/src/main/scala/it/cwmp/view/View.scala
- https://trello.com/c/ueJURV4L
=> [SPRINT2] Basic skeleton of the client interface (with few abstractions)

core/src/main/scala/it/cwmp/authentication/AuthenticationService.scala, core/src/test/scala/it/cwmp/authentication/AuthenticationServiceTest.scala, server/authentication/src/test/scala/it/cwmp/authentication/AuthenticationServiceVerticleTest.scala
- Renamed test that had same name
- Improved AuthorizationService class wrapping default values, and letting user choose whether to specify
- Solved warnings in AuthenticationServiceTest
=> AuthorizationService usability improvement

.gitignore, client/build.gradle, client/build.sbt, client/project/build.properties, client/project/plugins.sbt, client/src/main/scala/ClientHelloMain.scala, client/src/main/scala/it/cwmp/client/model/ReplicatedCache.scala, client/src/multi-jvm/scala/it/cwmp/client/model/ReplicatedCacheSpec.scala, client/src/multi-jvm/scala/it/cwmp/client/model/STMultiNodeSpec.scala
- [IT11] https://trello.com/c/Ni3OnKwv
- https://doc.akka.io/docs/akka/2.5/distributed-data.html?language=scala
=> [SPRINT2] predisposto client (sbt) per demo akka distributed data

client/src/main/resources/createPrivateRoomLayout.fxml, client/src/main/resources/enterPrivateRoomLayout.fxml, client/src/main/resources/listCellItem.fxml, client/src/main/resources/privateTabLayout.fxml, client/src/main/resources/publicTabLayout.fxml, client/src/main/resources/roomManagerLayout.fxml, client/src/main/scala/it/cwmp/CreatePrivateRoomMain.scala, client/src/main/scala/it/cwmp/RoomManagerMain.scala, client/src/main/scala/it/cwmp/controller/CreatePrivateRoomController.scala, client/src/main/scala/it/cwmp/controller/RoomsManagerController.scala, client/src/main/scala/it/cwmp/utils/LayoutRes.scala, client/src/main/scala/it/cwmp/utils/StringRes.scala, client/src/main/scala/it/cwmp/view/CreatePrivateRoomView.scala, client/src/main/scala/it/cwmp/view/RoomsManagerView.scala
- [IT6] https://trello.com/c/J3sBtXpE
- [IT7] https://trello.com/c/9IMD4aLD
- [IT8] https://trello.com/c/pudKTrA7
=> [SPRINT2] Implementazione della GUI per gestire la creazione/entrata in una stanza pub/priv

build.gradle, doc/agile/Sprint3 backlog.md, server/rooms/src/main/scala/it/cwmp/controller/rooms/RoomsLocalDAO.scala, server/rooms/src/test/scala/it/cwmp/controller/rooms/RoomsServiceVerticleTest.scala
Trying to correct non-deterministic test fails, i've tried to reduce reused resources.
Maybe this way Connection Closed errors during tests, should not appear.
https://trello.com/c/5olCkniL
=> [SPRINT3] Trying to correct spurious tests fail

client/src/main/resources/layouts/RoomManagerLayout.fxml, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/model/ApiClientActor.scala, client/src/main/scala/it/cwmp/client/view/AlertActor.scala, client/src/main/scala/it/cwmp/client/view/FXAlerts.scala, client/src/main/scala/it/cwmp/client/view/FXChecks.scala, client/src/main/scala/it/cwmp/client/view/FXController.scala, client/src/main/scala/it/cwmp/client/view/room/RoomFXController.scala, client/src/main/scala/it/cwmp/client/view/room/RoomViewActor.scala, client/src/test/scala/it/cwmp/client/controller/ClientControllerActorTest.scala
- [IT3] https://trello.com/c/J3sBtXpE
=> [SPRINT3] Completato struttura client per creazione stanza

client/src/main/resources/layouts/RoomManagerLayout.fxml, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/model/ApiClientActor.scala, client/src/main/scala/it/cwmp/client/view/room/RoomFXController.scala, client/src/main/scala/it/cwmp/client/view/room/RoomViewActor.scala
- [IT4] https://trello.com/c/9IMD4aLD/
=> [SPRINT3] Implementata la possibilità di entrare in una stanza privata

client/build.gradle, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/model/ApiClientActor.scala, client/src/main/scala/it/cwmp/client/model/ParticipantListReceiver.scala, client/src/main/scala/it/cwmp/client/model/PlayerActor.scala, server/room-receiver/src/main/scala/it/cwmp/roomreceiver/controller/RoomReceiverServiceVerticle.scala
- [IT11] https://trello.com/c/UOCfx0zS
=> [SPRINT3] Aggiunto attore per il gioco distribuito lato client

client/src/main/resources/layouts/RoomManagerLayout.fxml, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/model/ApiClientActor.scala, client/src/main/scala/it/cwmp/client/view/room/RoomFXController.scala, client/src/main/scala/it/cwmp/client/view/room/RoomViewActor.scala
- [IT5] https://trello.com/c/pudKTrA7
=> [SPRINT3] Implementata connessione alle stanze pubbliche nel client

client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/model/ApiClientActor.scala, client/src/main/scala/it/cwmp/client/model/ParticipantListReceiver.scala, core/src/main/scala/it/cwmp/controller/client/RoomReceiverApiWrapper.scala, core/src/main/scala/it/cwmp/controller/rooms/RoomsApiWrapper.scala, core/src/main/scala/it/cwmp/model/Address.scala, core/src/main/scala/it/cwmp/model/Participant.scala, core/src/test/scala/it/cwmp/controller/rooms/RoomsApiWrapperTest.scala, server/rooms/src/main/scala/it/cwmp/controller/rooms/RoomsLocalDAO.scala, server/rooms/src/main/scala/it/cwmp/controller/rooms/RoomsServiceVerticle.scala, server/rooms/src/test/scala/it/cwmp/controller/rooms/RoomsLocalDAOTest.scala, server/rooms/src/test/scala/it/cwmp/controller/rooms/RoomsServiceVerticleTest.scala, server/testing/src/main/scala/it/cwmp/testing/server/rooms/RoomsWebServiceTesting.scala
Added the ability to send an additiona address different from player address that is used server-side to send participant list to clients
- Added Address as a standalone instantiable class
- Refactored model classes
- Rewritten tests adapting to new modifications
https://trello.com/c/7schjKE7
=> [SPRINT3] Address refactoring

client/src/main/scala/it/cwmp/client/view/game/GameFX.scala, client/src/main/scala/it/cwmp/client/view/game/ObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/model/Cell.scala, client/src/main/scala/it/cwmp/client/view/game/model/Point.scala
-[IT15] https://trello.com/c/1s8hpYka
=> [SPRINT3] Creato engine di base per visualizzare lo stato di gioco

client/src/main/resources/application.conf, client/src/main/scala/it/cwmp/client/model/ApiClientActor.scala, client/src/main/scala/it/cwmp/client/model/PlayerActor.scala, core/src/main/scala/it/cwmp/authentication/AuthenticationService.scala, core/src/main/scala/it/cwmp/authentication/HttpValidation.scala, core/src/main/scala/it/cwmp/controller/rooms/RoomsApiWrapper.scala, server/rooms/src/main/scala/it/cwmp/controller/rooms/RoomsServiceVerticle.scala, server/testing/src/main/scala/it/cwmp/testing/server/rooms/RoomsWebServiceTesting.scala
- https://trello.com/c/UOCfx0zS implementato hello world da testare
- corretto passaggio del token di autenticazione dalle room
- rifattorizzato il participant in address dove non ancora fatto
=> [SPRINT3] Bug resolution and cluster structure implementation

client/src/main/scala/it/cwmp/client/view/game/GameFX.scala, client/src/main/scala/it/cwmp/client/view/game/ObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/model/Cell.scala
- [IT16] https://trello.com/c/71EBIOjC/
=> [SPRINT3] implementato la visualizzazione degli oggetti di gioco nell'engine

client/src/main/scala/it/cwmp/client/ClientMain.scala, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/model/ParticipantListReceiver.scala, client/src/main/scala/it/cwmp/client/model/PlayerActor.scala, core/src/main/scala/it/cwmp/controller/client/RoomReceiverApiWrapper.scala, server/room-receiver/src/main/scala/it/cwmp/roomreceiver/controller/RoomReceiverServiceVerticle.scala, server/room-receiver/src/test/scala/it/cwmp/roomreceiver/controller/RoomReceiverServiceVerticleTest.scala
Ora i client si connettono tra di loro alla ricezione della lista
=> [SPRINT3] Completato configurazione cluster

client/build.gradle, client/src/main/scala/it/cwmp/client/GameMain.scala, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/model/PlayerActor.scala, client/src/main/scala/it/cwmp/client/view/game/GameActor.scala, client/src/main/scala/it/cwmp/client/view/game/GameFX.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewActor.scala, client/src/main/scala/it/cwmp/client/view/game/ObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/model/ViewCell.scala, client/src/main/scala/it/cwmp/client/view/room/RoomViewActor.scala
- [IT17] https://trello.com/c/6Xe9Bxm1 la view è wrappata all'interno di un attore che la disegna a partire da un World di gioco.
- La gui viene avviata quando il cluster si riempe e la partita viene avviata.
=> [SPRINT3] Collegata la GUI di gioco al player actor e fatto in modo che disegni il World passato

client/src/main/scala/it/cwmp/client/controller/game/GameEngine.scala, client/src/main/scala/it/cwmp/client/model/game/EvolutionStrategy.scala, client/src/main/scala/it/cwmp/client/model/game/World.scala, client/src/main/scala/it/cwmp/client/model/game/impl/Cell.scala, client/src/main/scala/it/cwmp/client/model/game/impl/CellWorld.scala, client/src/main/scala/it/cwmp/client/model/game/impl/Point.scala, client/src/main/scala/it/cwmp/client/model/game/impl/Tentacle.scala, client/src/main/scala/it/cwmp/client/view/game/ColoringStrategy.scala, client/src/main/scala/it/cwmp/client/view/game/model/CellView.scala, client/src/main/scala/it/cwmp/client/view/game/model/TentacleView.scala, client/src/test/scala/it/cwmp/client/controller/game/GameEngineTest.scala, client/src/test/scala/it/cwmp/client/model/game/impl/CellTest.scala, client/src/test/scala/it/cwmp/client/model/game/impl/CellWorldTest.scala, client/src/test/scala/it/cwmp/client/model/game/impl/TentacleTest.scala
- Implemented GameEngine and its tests
- Added some manipulator implicits to model classes
=> [SPRINT4] GameEngine implementation and testing

client/src/main/scala/it/cwmp/client/model/ApiClientActor.scala, core/src/main/scala/it/cwmp/exceptions/HTTPException.scala, core/src/main/scala/it/cwmp/services/wrapper/AuthenticationApiWrapper.scala, core/src/main/scala/it/cwmp/services/wrapper/RoomsApiWrapper.scala, core/src/main/scala/it/cwmp/utils/VertxClient.scala, services/room-receiver/src/test/scala/it/cwmp/services/roomreceiver/RoomReceiverServiceVerticleTest.scala, services/rooms/src/main/scala/it/cwmp/services/rooms/RoomsServiceVerticle.scala
- [IT7] https://trello.com/c/FVOwJT2e
=> [SPRINT4] HttpException refactoring

core/src/main/scala/it/cwmp/utils/VertxServer.scala, services/authentication/src/main/scala/it/cwmp/services/authentication/AuthenticationServiceMain.scala, services/authentication/src/main/scala/it/cwmp/services/authentication/AuthenticationServiceVerticle.scala, services/room-receiver/src/main/scala/it/cwmp/services/roomreceiver/RoomReceiverServiceVerticle.scala, services/rooms/src/main/scala/it/cwmp/services/rooms/RoomsServiceMain.scala, services/rooms/src/main/scala/it/cwmp/services/rooms/RoomsServiceVerticle.scala
- [IT4] https://trello.com/c/mV6vyw58
completato il refactoring dei vertx server
=> [SPRINT4] Refactoring server

client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/model/ApiClientActor.scala, core/src/main/scala/it/cwmp/exceptions/HTTPException.scala
- Integrated HTTPException in with Exception Framework overriding right method *getMessage* of `Throwable` class
- Solved annoying warnings in Client actors
=> [SPRINT4] HTTPException Improvement

client/src/main/scala/it/cwmp/client/controller/game/GameConstants.scala, client/src/main/scala/it/cwmp/client/controller/game/GameEngine.scala, client/src/main/scala/it/cwmp/client/model/game/impl/Cell.scala, client/src/main/scala/it/cwmp/client/model/game/impl/CellWorld.scala, client/src/main/scala/it/cwmp/client/model/game/impl/Tentacle.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewConstants.scala, client/src/main/scala/it/cwmp/client/view/game/model/CellView.scala, client/src/test/scala/it/cwmp/client/model/game/impl/GeometricUtilsTest.scala
Moved all GameConstants in an object, so they are easy to retrieve
=> [SPRINT4] Collected GameConstants

build.gradle
Coverage reports non vengono caricati.
=> Sprint 4 - closed (fix)

client/src/main/scala/it/cwmp/client/view/game/GameViewActor.scala, client/src/test/scala/it/cwmp/client/model/game/impl/GeometricUtilsTest.scala
- Added messages that GUI can send to actor notifying for user actions
=> [SPRINT5] Prepared GameViewActor for GUI interaction

client/src/main/scala/it/cwmp/client/view/game/GameFX.scala, client/src/main/scala/it/cwmp/client/view/game/ObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/model/CellView.scala
- [IT3] https://trello.com/c/4I4lLLD7
- [IT8] https://trello.com/c/A2vQdanc
=> [SPRINT5]Visualizzata energia nella cella e risolto bug ridimensionamento celle

client/src/main/scala/it/cwmp/client/GameMain.scala, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/controller/game/GameConstants.scala, client/src/main/scala/it/cwmp/client/controller/game/GameEngine.scala, client/src/main/scala/it/cwmp/client/model/CellWorldDistributedState.scala, client/src/main/scala/it/cwmp/client/model/DistributedState.scala, client/src/main/scala/it/cwmp/client/model/PlayerActor.scala, client/src/main/scala/it/cwmp/client/model/game/impl/GeometricUtils.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewActor.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewConstants.scala, client/src/main/scala/it/cwmp/client/view/game/ObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/model/CellView.scala, client/src/main/scala/it/cwmp/client/view/game/model/TentacleView.scala, client/src/test/scala/it/cwmp/client/model/game/impl/GeometricUtilsTest.scala
- Added some GeometricUtils methods to help managing the retrieval of informations coming from View (and related tests)
- Added behaviour for GameViewActor in response to AddAttack and RemoveAttack messages
- Generified DistributedState class
- Created a specific version of DistributedState class to manage CellWorld
- Added some comments to classes and moved companions below the classes
- Made JavaFX colors default
[IT1] https://trello.com/c/qimGTZaq
=> [SPRINT5] GameViewActor GUI Integration

client/src/main/scala/it/cwmp/client/model/game/GeometricUtils.scala, client/src/main/scala/it/cwmp/client/view/game/GameFX.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewConstants.scala, client/src/main/scala/it/cwmp/client/view/game/ObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/model/CellView.scala
- Added some constant values for Font color and Size
- Added field to CellView to piggyback the color for energy text, calculated by an introduced strategy
- Modified sizing strategy to have minimum and maximum sizes
[IT4] https://trello.com/c/IK4ANJcP
=> [SPRINT5] Cell View Proper Sizing

client/src/main/scala/it/cwmp/client/model/DistributedState.scala, client/src/main/scala/it/cwmp/client/model/ParticipantListReceiver.scala, client/src/main/scala/it/cwmp/client/model/game/impl/Cell.scala, client/src/main/scala/it/cwmp/client/model/game/impl/CellWorld.scala, client/src/main/scala/it/cwmp/client/model/game/impl/Tentacle.scala, client/src/main/scala/it/cwmp/client/view/game/CellWorldObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/GameFX.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewActor.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewConstants.scala, client/src/main/scala/it/cwmp/client/view/game/ObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/model/CellView.scala, client/src/main/scala/it/cwmp/client/view/game/model/TentacleView.scala, client/src/test/scala/it/cwmp/client/model/game/impl/CellTest.scala, client/src/test/scala/it/cwmp/client/model/game/impl/CellWorldTest.scala, client/src/test/scala/it/cwmp/client/model/game/impl/TentacleTest.scala, services/authentication/src/test/scala/it/cwmp/services/authentication/AuthenticationLocalDAOTest.scala
- Added `case class TentacleView` to wrap the view of Tentacles
- Partitioned behaviour of `GameViewActor`
- Replaced magic numbers with constants
- Added documentation
=> [SPRINT5] Little Refactoring of client Model and ViewModel

client/src/main/scala/it/cwmp/client/view/game/CellWorldObjectDrawer.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewConstants.scala
- [IT5] https://trello.com/c/CfdhBtyx
=> [SPRINT5] Aggiunta la trasparenza per l'instnant

client/src/main/resources/layouts/roomManagerLayout.fxml, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/view/AlertActor.scala, client/src/main/scala/it/cwmp/client/view/FXController.scala, client/src/main/scala/it/cwmp/client/view/FXLoadingDialog.scala, client/src/main/scala/it/cwmp/client/view/authentication/AuthenticationFXController.scala, client/src/main/scala/it/cwmp/client/view/authentication/AuthenticationViewActor.scala, client/src/main/scala/it/cwmp/client/view/room/RoomFXController.scala, client/src/main/scala/it/cwmp/client/view/room/RoomViewActor.scala
- https://trello.com/c/Z1rxUmVd/
=> [SPRINT5] corretto bug della gui

client/src/main/scala/it/cwmp/client/view/FXViewController.scala, client/src/main/scala/it/cwmp/client/view/game/GameFX.scala
- [IT8] https://trello.com/c/QSYb9uge
=> [SPRINT6] disabilitata la possibilità di fare resize nelle finestre del gioco

client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/view/room/RoomViewActor.scala
Solved the problem of dialogs still open after finding opponents
=> [SPRINT6] BUGFIX Loading Dialog

client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/controller/messages/AuthenticationCommon.scala, client/src/main/scala/it/cwmp/client/controller/messages/RoomsCommon.scala, client/src/main/scala/it/cwmp/client/view/room/RoomFXController.scala, client/src/main/scala/it/cwmp/client/view/room/RoomStrategy.scala, client/src/main/scala/it/cwmp/client/view/room/RoomViewActor.scala
- [IT1] https://trello.com/c/raCyLgCm/
=> [SPRINT6] Return to authentication view from room view

client/src/main/scala/it/cwmp/client/controller/ApiClientActor.scala, client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala
- [IT5] https://trello.com/c/CnIyuNAJ/
=> [SPRINT6] Interruzione dell'entrata in una stanza

client/src/main/resources/layouts/authenticationManagerLayout.fxml, client/src/main/resources/layouts/roomManagerLayout.fxml
- https://trello.com/c/LIUYlaLH/
=> [SPRINT6] Fixata dimensione dei pane della GUI

client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/view/game/GameFX.scala
- Removed TODOs
- Added stopping the one-time server after room exiting
[IT6] https://trello.com/c/2da6Sccj
=> [SPRINT6] Close one-time server after exiting room

client/src/main/scala/it/cwmp/client/controller/ApiClientActor.scala, client/src/main/scala/it/cwmp/client/controller/PlayerActor.scala, client/src/main/scala/it/cwmp/client/controller/messages/AuthenticationCommon.scala, client/src/main/scala/it/cwmp/client/controller/messages/Common.scala, client/src/main/scala/it/cwmp/client/controller/messages/Initialize.scala, client/src/main/scala/it/cwmp/client/controller/messages/RoomsCommon.scala, client/src/main/scala/it/cwmp/client/view/room/RoomViewActor.scala
- Created some base messages types (Request, GUIRequest, ToServiceRequest, Response)
- Moved "Initialize" message among those commonly used messages
- Removed unused LogOut message from AuthenticationCommon
=> [SPRINT6] Actor Messages hierarchy refactoring

client/src/main/scala/it/cwmp/client/view/game/GameFX.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewActor.scala
Moved heavy computations away from Akka Thread in `GameViewActor` and from JavaFX GUI thread in `GameFX`
=> [SPRINT6] Moved heavy computations away from main threads

client/src/main/scala/it/cwmp/client/controller/ClientControllerActor.scala, client/src/main/scala/it/cwmp/client/controller/PlayerActor.scala, client/src/main/scala/it/cwmp/client/view/game/GameFX.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewActor.scala
Found that you **cannot leave a cluster** and join another **without restarting entire actorSystem**, so a complete restart is needed, and it's a no sense to return to rooms view as it will not work properly.
- Refactored methods and reformatted code
- Added removal TODO for useless behaviours/methods at light of this discovery
=> [SPRINT6] GameView come Back investigation

client/src/main/scala/it/cwmp/client/view/game/GameViewActor.scala, client/src/main/scala/it/cwmp/client/view/game/model/TentacleView.scala
- Solved bug for which removing a tentacle that is over another was not permitted
- Made tentacles a little bit trasparent
=> [SPRINT7] Tentacle GUI Fixes

build.gradle
- https://trello.com/c/cXWrMy69
=> [SPRINT7] Logic of the creation of the doc folders

client/build.gradle, client/src/main/resources/application.conf
Replaced Java Serialization of distributed classes with a faster and lighter serialization (**Kryo**)
https://github.com/romix/akka-kryo-serialization
=> [SPRINT7] Distributed Classes serialization

client/src/main/scala/it/cwmp/client/controller/game/GameConstants.scala, client/src/main/scala/it/cwmp/client/view/game/GameViewActor.scala
- Added GameConstants to set minimum and maximum time between two client synchronizations
- Added waitTime calculation in GameViewActor
- Added a method to start/restart synchronization schedule
- Added a message to tell "synchronize current world"
- Made Actor restart timer every user or external modification of world
=> [SPRINT7] Client Periodic Synchronization

client/src/main/scala/it/cwmp/client/ClientMain.scala
Client now asks for it's IP but it's not used inside ClientMain... still TODO
=> [SPRINT8] Client Asks for it's IP
